// <auto-generated />
using ECommerceASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceASP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceASP.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "Chaussure"
                        },
                        new
                        {
                            Id = 2,
                            name = "Pantalon"
                        },
                        new
                        {
                            Id = 3,
                            name = "Chemise"
                        });
                });

            modelBuilder.Entity("ECommerceASP.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Nike Air",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Adidas Run",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Puma Sport",
                            Price = 90.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Reebok Classic",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Converse All Star",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Jean Slim",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "Chino Beige",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Jogging Noir",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Short Sport",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Pantalon Cargo",
                            Price = 70.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "Chemise Blanche",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Chemise à Carreaux",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "Chemise Jean",
                            Price = 55.00m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Name = "Chemise Lin",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Name = "Chemise Noire",
                            Price = 48.00m
                        });
                });

            modelBuilder.Entity("ECommerceASP.Models.Product", b =>
                {
                    b.HasOne("ECommerceASP.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
